// Prism AI — PRD Generator. Produces a complete, build-ready Product
// Requirements Document from an Evolution concept. Generated in two focused
// passes (product + engineering) for depth, then stitched into one document.
import { createClientFromRequest } from "npm:@base44/sdk";

Deno.serve(async (req) => {
  const base44 = createClientFromRequest(req);
  const user = await base44.auth.me().catch(() => null);
  if (!user) return Response.json({ error: "Unauthorized" }, { status: 401 });

  let body: { projectId?: string; evolutionId?: string } = {};
  try {
    body = await req.json();
  } catch {
    // fallthrough
  }
  const { projectId, evolutionId } = body;
  if (!projectId || !evolutionId) {
    return Response.json({ error: "projectId and evolutionId are required" }, { status: 400 });
  }

  const [project, evolution] = await Promise.all([
    base44.entities.Project.get(projectId).catch(() => null),
    base44.entities.Evolution.get(evolutionId).catch(() => null),
  ]);
  if (!project || !evolution) {
    return Response.json({ error: "Project or evolution not found" }, { status: 404 });
  }

  const concept = JSON.stringify(evolution.data, null, 2);
  const marketContext = JSON.stringify(
    {
      analyzed_product: project.product_name,
      category: project.category,
      overview: project.overview,
      layer_scores: project.layer_scores,
    },
    null,
    2,
  );

  const shared = `You are Prism AI's PRD engine writing a production-grade Product Requirements Document for "${evolution.title}" — an original product concept born from analyzing ${project.product_name}.

The PRD must be detailed enough that an AI coding agent could build the product from it alone. Write in clean markdown with ## section headers and ### subsections. Be specific: real field names, real flows, real priorities. No filler like "this section describes...".

PRODUCT CONCEPT:
${concept}

MARKET CONTEXT (from the analysis that inspired this concept):
${marketContext}`;

  const productPass = `${shared}

Write ONLY these sections, in this order:

## 1. Product Vision
## 2. Problem Statement
## 3. User Personas
(3 personas: name, role, context, pains, gains, quote)
## 4. User Journeys
(the 3 most important end-to-end journeys, step by step)
## 5. Features & Requirements
(every feature with: description, user stories, acceptance criteria)
## 6. Feature Prioritization
(MoSCoW table: Must / Should / Could / Won't for v1)

Start directly with "## 1. Product Vision".`;

  const engineeringPass = `${shared}

Write ONLY these sections, in this order (continue numbering from 7):

## 7. Database Structure
(every entity with fields, types, and relationships — use tables)
## 8. Backend Architecture
(services, background jobs, pipelines, rate limiting)
## 9. API Requirements
(each endpoint: method, path, payload, response, auth)
## 10. Authentication & Permissions
(auth flows, roles, row-level access rules)
## 11. AI Systems
(each AI feature: model role, prompt strategy, structured outputs, fallbacks)
## 12. Notifications
## 13. Analytics & Success Metrics
(events to track, KPIs, north star)
## 14. Edge Cases & Error Handling
## 15. Launch Plan
(pre-launch, launch week, post-launch)
## 16. Future Roadmap
(v1.1 through v2.0)

Start directly with "## 7. Database Structure".`;

  try {
    const [part1, part2] = await Promise.all([
      base44.integrations.Core.InvokeLLM({ prompt: productPass }),
      base44.integrations.Core.InvokeLLM({ prompt: engineeringPass }),
    ]);
    const toText = (r: unknown) => (typeof r === "string" ? r : JSON.stringify(r));
    const content = `# ${evolution.title} — Product Requirements Document\n\n> Generated by Prism AI from the analysis of ${project.product_name}.\n\n${toText(part1).trim()}\n\n${toText(part2).trim()}\n`;

    // Entity string fields are size-capped (~16-24k chars), so a full PRD is
    // stored as an ordered group of chunk rows split at paragraph boundaries.
    const CHUNK = 14000;
    const chunks: string[] = [];
    let buf = "";
    for (const para of content.split("\n")) {
      if (buf.length + para.length + 1 > CHUNK && buf) {
        chunks.push(buf);
        buf = "";
      }
      buf += (buf ? "\n" : "") + para;
    }
    if (buf) chunks.push(buf);

    const groupId = crypto.randomUUID();
    let firstId = "";
    for (let i = 0; i < chunks.length; i++) {
      const row = await base44.entities.Prd.create({
        project_id: projectId,
        evolution_id: evolutionId,
        title: `${evolution.title} PRD`,
        content: chunks[i],
        group_id: groupId,
        part: i,
        parts_total: chunks.length,
      });
      if (i === 0) firstId = row.id;
    }
    return Response.json({ ok: true, prdId: firstId, parts: chunks.length });
  } catch (err) {
    return Response.json({ error: String(err?.message || err) }, { status: 500 });
  }
});
