// DEV-ONLY: renders a report generated by the current Groq pipeline, so the
// output judges will actually see can be inspected in the real UI.
import fixture from "./fixture-groq.json";
import ReportView from "@/components/report/ReportView";

export default function DevGroq() {
  const tab = new URLSearchParams(window.location.search).get("tab") || "overview";
  return (
    <div className="max-w-7xl mx-auto px-5 py-8">
      <ReportView
        project={fixture.project}
        sections={fixture.sections}
        onRefresh={() => {}}
        initialTab={tab}
      />
    </div>
  );
}
